version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: opencv-stubs
    path: ./.github/config/opencv-stubs.dict
    addWords: true
dictionaries:
  - opencv-stubs
words: []
ignoreWords: []
import: []
