name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "**.pyi"
      - "**.py"
      - .github/workflows/pre-commit.yaml
      - pyproject.toml
  pull_request:
    paths:
      - "**.pyi"
      - "**.py"
      - .github/workflows/pre-commit.yaml
      - pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
      - run: uv run pre-commit run --all-files
